"""add variant_metrics

Revision ID: 75009967037e
Revises: 3025bb449185
Create Date: 2026-02-18 20:33:55.044681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75009967037e'
down_revision: Union[str, Sequence[str], None] = '3025bb449185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('mean_expectancy', sa.Float(), nullable=False),
    sa.Column('std_expectancy', sa.Float(), nullable=False),
    sa.Column('mean_sharpe', sa.Float(), nullable=False),
    sa.Column('std_sharpe', sa.Float(), nullable=False),
    sa.Column('mean_win_rate', sa.Float(), nullable=False),
    sa.Column('mean_volatility', sa.Float(), nullable=False),
    sa.Column('worst_max_dd', sa.Float(), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant_metrics')
    # ### end Alembic commands ###
