"""phase 4 portfolio governance

Revision ID: 2afacec8f9ad
Revises: 78ffe1e86eb8
Create Date: 2026-02-24

not autogenerated!

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy.dialects import postgresql
import uuid
from datetime import datetime

# revision identifiers
revision: str = "2afacec8f9ad"
down_revision: Union[str, Sequence[str], None] = "78ffe1e86eb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ---------------------------------------------------------
    # 1️⃣ Create portfolios table
    # ---------------------------------------------------------

    op.create_table(
        "portfolios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_dirty", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_portfolios_user_name"),
    )

    op.create_index("ix_portfolios_user_id", "portfolios", ["user_id"])

    # ---------------------------------------------------------
    # 2️⃣ Add portfolio_id column as nullable first
    # ---------------------------------------------------------

    op.add_column(
        "strategies",
        sa.Column("portfolio_id", sa.UUID(), nullable=True),
    )

    # ---------------------------------------------------------
    # 3️⃣ Backfill existing data
    # ---------------------------------------------------------

    bind = op.get_bind()
    session = Session(bind=bind)

    users = session.execute(sa.text("SELECT id FROM users")).fetchall()

    for row in users:
        user_id = row[0]
        default_id = uuid.uuid4()

        session.execute(
            sa.text("""
                INSERT INTO portfolios
                (id, user_id, name, is_default, is_dirty, created_at, updated_at)
                VALUES
                (:id, :user_id, :name, :is_default, :is_dirty, :created_at, :updated_at)
            """),
            {
                "id": default_id,
                "user_id": user_id,
                "name": "Default",
                "is_default": True,
                "is_dirty": True,
                "created_at": datetime.utcnow(),
                "updated_at": datetime.utcnow(),
            }
        )

        session.execute(
            sa.text("""
                UPDATE strategies
                SET portfolio_id = :pid
                WHERE user_id = :uid
            """),
            {
                "pid": default_id,
                "uid": user_id,
            }
        )

    session.commit()

    # ---------------------------------------------------------
    # 4️⃣ Make column NOT NULL + add FK + index
    # ---------------------------------------------------------

    op.alter_column(
        "strategies",
        "portfolio_id",
        nullable=False,
    )

    op.create_index(
        "ix_strategies_portfolio_id",
        "strategies",
        ["portfolio_id"],
    )

    op.create_foreign_key(
        "fk_strategies_portfolio_id",
        "strategies",
        "portfolios",
        ["portfolio_id"],
        ["id"],
    )


def downgrade() -> None:

    op.drop_constraint("fk_strategies_portfolio_id", "strategies", type_="foreignkey")
    op.drop_index("ix_strategies_portfolio_id", table_name="strategies")
    op.drop_column("strategies", "portfolio_id")

    op.drop_index("ix_portfolios_user_id", table_name="portfolios")
    op.drop_table("portfolios")