"""add tenant-aware constraints and user_id indexes

Revision ID: 39c0e0c077de
Revises: 1d7457fbeaaf
Create Date: 2026-02-20 17:09:03.154130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c0e0c077de'
down_revision: Union[str, Sequence[str], None] = '1d7457fbeaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_run_metrics_user_id', 'run_metrics', ['user_id'], unique=False)
    op.create_index('ix_runs_user_id', 'runs', ['user_id'], unique=False)
    op.create_index('ix_strategies_user_id', 'strategies', ['user_id'], unique=False)
    op.create_unique_constraint('uq_strategies_user_name', 'strategies', ['user_id', 'name'])
    op.create_index('ix_trades_user_id', 'trades', ['user_id'], unique=False)
    op.create_index('ix_variant_metrics_user_id', 'variant_metrics', ['user_id'], unique=False)
    op.create_index('ix_variants_user_id', 'variants', ['user_id'], unique=False)
    op.create_unique_constraint('uq_variants_user_name', 'variants', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_variants_user_name', 'variants', type_='unique')
    op.drop_index('ix_variants_user_id', table_name='variants')
    op.drop_index('ix_variant_metrics_user_id', table_name='variant_metrics')
    op.drop_index('ix_trades_user_id', table_name='trades')
    op.drop_constraint('uq_strategies_user_name', 'strategies', type_='unique')
    op.drop_index('ix_strategies_user_id', table_name='strategies')
    op.drop_index('ix_runs_user_id', table_name='runs')
    op.drop_index('ix_run_metrics_user_id', table_name='run_metrics')
    # ### end Alembic commands ###
