"""add description to variant and run

Revision ID: 45ea4f93c590
Revises: 39c0e0c077de
Create Date: 2026-02-21 23:18:50.527500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ea4f93c590'
down_revision: Union[str, Sequence[str], None] = '39c0e0c077de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('variants', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variants', 'description')
    op.drop_column('runs', 'description')
    # ### end Alembic commands ###
