"""add variant_analytics table

Revision ID: 70de3272e6c3
Revises: d95ab70e3bf2
Create Date: 2026-02-23 15:00:01.914539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70de3272e6c3'
down_revision: Union[str, Sequence[str], None] = 'd95ab70e3bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('aggregated_metrics_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('is_dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'variant_id', name='uq_variant_analytics_user_variant')
    )
    op.create_index('ix_variant_analytics_user_id', 'variant_analytics', ['user_id'], unique=False)
    op.create_index('ix_variant_analytics_variant_id', 'variant_analytics', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_variant_analytics_variant_id', table_name='variant_analytics')
    op.drop_index('ix_variant_analytics_user_id', table_name='variant_analytics')
    op.drop_table('variant_analytics')
    # ### end Alembic commands ###
