"""add strategy and portfolio analytics

Revision ID: 78ffe1e86eb8
Revises: 70de3272e6c3
Create Date: 2026-02-23 16:38:56.975404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78ffe1e86eb8'
down_revision: Union[str, Sequence[str], None] = '70de3272e6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allocation_mode', sa.String(length=50), nullable=False),
    sa.Column('allocation_config_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('combined_metrics_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('combined_equity_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('strategy_count', sa.Integer(), nullable=False),
    sa.Column('is_dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_index('ix_portfolio_analytics_user_id', 'portfolio_analytics', ['user_id'], unique=False)
    op.create_table('strategy_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('aggregated_metrics_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('variant_count', sa.Integer(), nullable=False),
    sa.Column('is_dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'strategy_id', name='uq_strategy_analytics_user_strategy')
    )
    op.create_index('ix_strategy_analytics_strategy_id', 'strategy_analytics', ['strategy_id'], unique=False)
    op.create_index('ix_strategy_analytics_user_id', 'strategy_analytics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategy_analytics_user_id', table_name='strategy_analytics')
    op.drop_index('ix_strategy_analytics_strategy_id', table_name='strategy_analytics')
    op.drop_table('strategy_analytics')
    op.drop_index('ix_portfolio_analytics_user_id', table_name='portfolio_analytics')
    op.drop_table('portfolio_analytics')
    # ### end Alembic commands ###
