"""add user model

Revision ID: a9c87acd5aac
Revises: da8ff8da8024
Create Date: 2026-02-20 16:17:34.448811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9c87acd5aac'
down_revision: Union[str, Sequence[str], None] = 'da8ff8da8024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # 1️⃣ Columns erstmal nullable=True hinzufügen
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))

    # 2️⃣ Defaults für bestehende User setzen
    op.execute("UPDATE users SET is_admin = FALSE WHERE is_admin IS NULL;")
    op.execute("UPDATE users SET is_active = TRUE WHERE is_active IS NULL;")
    op.execute("UPDATE users SET password_hash = '' WHERE password_hash IS NULL;")

    # 3️⃣ Danach NOT NULL erzwingen
    op.alter_column('users', 'password_hash', nullable=False)
    op.alter_column('users', 'is_admin', nullable=False)
    op.alter_column('users', 'is_active', nullable=False)

    # Email Index sauber setzen
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
