"""trade model extended

Revision ID: d48d28e32ebc
Revises: d642f6cb92e4
Create Date: 2026-02-20 01:29:45.158014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48d28e32ebc'
down_revision: Union[str, Sequence[str], None] = 'd642f6cb92e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('strategies', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('variants', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variants', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('strategies', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('runs', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
