"""add run_analytics table

Revision ID: d95ab70e3bf2
Revises: 45ea4f93c590
Create Date: 2026-02-22 01:02:46.021328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd95ab70e3bf2'
down_revision: Union[str, Sequence[str], None] = '45ea4f93c590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_analytics',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('run_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('metrics_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('equity_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('walk_forward_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('monte_carlo_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_of_ruin_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('regime_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('kelly_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_dirty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'run_id', name='uq_run_analytics_user_run')
    )
    op.create_index('ix_run_analytics_run_id', 'run_analytics', ['run_id'], unique=False)
    op.create_index('ix_run_analytics_user_id', 'run_analytics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_analytics_user_id', table_name='run_analytics')
    op.drop_index('ix_run_analytics_run_id', table_name='run_analytics')
    op.drop_table('run_analytics')
    # ### end Alembic commands ###
