"""trade model v2

Revision ID: da8ff8da8024
Revises: d48d28e32ebc
Create Date: 2026-02-20 01:36:22.131972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8ff8da8024'
down_revision: Union[str, Sequence[str], None] = 'd48d28e32ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('stop_loss', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('timeframe', sa.String(length=10), nullable=True))
    op.add_column('trades', sa.Column('r_multiple', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('is_win', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'is_win')
    op.drop_column('trades', 'r_multiple')
    op.drop_column('trades', 'timeframe')
    op.drop_column('trades', 'timestamp')
    op.drop_column('trades', 'stop_loss')
    # ### end Alembic commands ###
